Feature diploma/new tests
Ladauser/TestRailDiploma pull request #7
Opened 2022-01-27 08:14 UTC by Ladauser

2022-01-28 15:29 UTC, vchesnakoutest requested changes

2022-01-28 15:29 UTC, vchesnakoutest commented on src/main/java/pages/RunsPage.java
> +    public boolean testResultWasAdded() {
isTestResultAdded

2022-01-28 15:29 UTC, vchesnakoutest commented on src/test/resources/features/ui_tests/RunPage.feature
> +    When User opens TestRail login page
And User opens TestRail login page

2022-01-28 15:29 UTC, vchesnakoutest commented on src/test/resources/features/ui_tests/RunPage.feature
> +    When User clicks login button
And User clicks login button

2022-01-28 15:29 UTC, vchesnakoutest commented on src/test/resources/features/ui_tests/RunPage.feature
> +    When User add new test case 'Result test' in section
And

2022-01-28 15:29 UTC, vchesnakoutest commented on src/test/resources/features/ui_tests/RunPage.feature
> +    And goes to the runs page and add the test result
When

2022-01-28 15:29 UTC, vchesnakoutest commented on src/test/resources/features/ui_tests/RunPage.feature
> +    And Verify test run was added
Then

2022-01-28 15:29 UTC, vchesnakoutest commented on src/test/resources/features/ui_tests/RunPage.feature
>      When User clicks login button
And

2022-01-28 15:29 UTC, vchesnakoutest commented on src/test/resources/features/ui_tests/RunPage.feature
>      Then goes to the project and add new test run
When

2022-01-29 10:14 UTC, Ladauser commented on src/main/java/pages/RunsPage.java
> +    public boolean testResultWasAdded() {
fixed

2022-01-29 13:34 UTC, vchesnakoutest requested changes

2022-01-29 13:34 UTC, vchesnakoutest commented on src/main/java/steps/CustomizationsSteps.java
> +        createRandomName();
👍

2022-01-29 13:34 UTC, vchesnakoutest commented on src/main/java/utils/Random.java
> +    public Random() {
private, т.к метод утилитный

2022-01-29 13:40 UTC, merged